# ---------- Stage 1: Build ----------
FROM node:24-alpine AS build
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci
COPY . .
# ---------- Stage 2: Production ----------
FROM node:24-alpine
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=build /usr/src/app ./
EXPOSE 3000
CMD ["node", "app.js"]
